name: zero_vendor
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.2
  shared_preferences: ^0.5.8
  geolocator: ^5.3.2+2
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^2.3.0
  animated_theme_switcher: "^1.0.5"
  curved_navigation_bar: ^0.3.3
  google_nav_bar: ^3.0.0
  file_picker: ^1.13.3
  flutter_svg: ^0.19.0
  form_builder_file_picker: ^0.3.0
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
